### PR TITLE
move over to linked list

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
This is starting to work pretty ok

**Comment by timholy** [comment]
I'll review in an hour or so if you wish (or just go ahead). I will use my bus ride to try to fix the error you noted [here](https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/127#issuecomment-471923375).

**Comment by KristofferC** [comment]
I'll start working on the tests. I'm sure a lot will come up... :D

**Comment by KristofferC** [comment]
Most of the tests here are actually now testing the implementation in JuliaInterpreter so should probably be moved. I'll work on making the tests pass and then move them over

**Comment by timholy** [comment]
Most of the tests have already been moved, see the current status of https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/126

**Comment by KristofferC** [comment]
All tests pass now with the exception of the UI tests because of the removal of `fullpath`. I don't really care much about being able to toggle fullpath or not with the exception that printing the full path makes the UI tests hard to make reproducible on different environments. Perhaps we can just hack in a toggle into JuliaInterpreter just for the testing here?

**Comment by KristofferC** [comment]
Alright, tests pass here now 🎉

**Comment by timholy** [comment]
If we need fullpath, IMO the implementation should be via `IOContext`. This package could set the IOContext appropriately and then JuliaInterpreter's show methods could look for it.

**Comment by KristofferC** [comment]
Sorry, I deleted the comment since I remembered that the choice of printing fullpath or not is actually in Debugger.jl not JuliaInterpreter. So I just added the flag here.

**Comment by KristofferC** [comment]
I should add tests with breakpoints but I will do that in another PR.

**Pull request merged**
