### PR TITLE
Step out of macro expansion

### PR DESCRIPTION
**Pull request by KristofferC**
```
julia> @enter f()
In f() at REPL[1]:2
2                 x = 1 + 1
3                 @debug "hello"
4                 z = sin(2.0)

About to run: (+)(1, 1)
1|debug> n
In f() at REPL[1]:2 (macro expansion)
303   
304       quote
305           level = $level
306           std_level = convert(LogLevel, level)
307           if std_level >= getindex(_min_enabled_level)
308               group = $group

About to run: (convert)(Base.CoreLogging.LogLevel, Debug)
1|debug> sm
In f() at REPL[1]:2
2                 x = 1 + 1
3                 @debug "hello"
4                 z = sin(2.0)
5                 return z
6             end

About to run: (sin)(2.0)
```

### CODE REVIEW

**Comment by pfitzseb** [comment]
I feel like stepping _over_ macro expansions would be the nicer default (and having `sm` for stepping into the expanded code), but this seems fine as well.

**Comment by KristofferC** [comment]
Yeah, that's also an alternative. At least the functionality is here to chose the default now.

**Comment by KristofferC** [comment]
So when we are in this situation:

```
1|debug> n
In f() at REPL[1]:2 (macro expansion)
303   
304       quote
305           level = $level
306           std_level = convert(LogLevel, level)
307           if std_level >= getindex(_min_enabled_level)
308               group = $group
```

We would instead show this as

```
In f() at REPL[1]:2
2                 x = 1 + 1
[3]                 @debug "hello"
4                 z = sin(2.0)
```

or something? And then you can step into that macro?

**Comment by staticfloat** [comment]
I think that as much as possible, it would be nice to treat macros like function calls that just happened to be inlined.  So you step into and out of them just like a function call.

**Comment by KristofferC** [comment]
That's an interesting idea. I like it!

**Comment by timholy** [comment]
xref https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/152

**Comment by KristofferC** [comment]
Stale

**Pull request closed without merging**
